package dw;

import Conexiones.Conexiones;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;




/**
 *
 * @author Informatica
 */
public class Inicio extends javax.swing.JFrame {

    Conexiones objConex;
     
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        objConex =new Conexiones();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonCalculaRM = new javax.swing.JButton();
        BotonCalculaPorcentaje = new javax.swing.JButton();
        BotonIntroducirEntreno = new javax.swing.JButton();
        BotonCalculaRitmos = new javax.swing.JButton();
        BotonTimer = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        BotonVerEntrenos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonCalculaRM.setText("Calcula RM");
        BotonCalculaRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCalculaRMActionPerformed(evt);
            }
        });

        BotonCalculaPorcentaje.setText("Calcula %");
        BotonCalculaPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCalculaPorcentajeActionPerformed(evt);
            }
        });

        BotonIntroducirEntreno.setText("Introducir Entreno");
        BotonIntroducirEntreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIntroducirEntrenoActionPerformed(evt);
            }
        });

        BotonCalculaRitmos.setText("Calcula Ritmos");
        BotonCalculaRitmos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCalculaRitmosActionPerformed(evt);
            }
        });

        BotonTimer.setText("Timer");
        BotonTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTimerActionPerformed(evt);
            }
        });

        BotonSalir.setText("Salir");

        BotonVerEntrenos.setText("Ver Entrenos");
        BotonVerEntrenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerEntrenosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonCalculaRM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonCalculaPorcentaje)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonCalculaRitmos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonTimer))
                            .addComponent(BotonIntroducirEntreno, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonVerEntrenos))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCalculaRM)
                    .addComponent(BotonCalculaPorcentaje)
                    .addComponent(BotonCalculaRitmos)
                    .addComponent(BotonTimer))
                .addGap(43, 43, 43)
                .addComponent(BotonIntroducirEntreno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonVerEntrenos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(BotonSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCalculaRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCalculaRMActionPerformed
        // TODO add your handling code here:
        CalculaRM a= new CalculaRM();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonCalculaRMActionPerformed

    private void BotonCalculaPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCalculaPorcentajeActionPerformed
        // TODO add your handling code here:
        CalculaPorcentaje a= new CalculaPorcentaje();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonCalculaPorcentajeActionPerformed

    private void BotonIntroducirEntrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIntroducirEntrenoActionPerformed
        // TODO add your handling code here:
              
        this.setVisible(false);
        String id = JOptionPane.showInputDialog("Ingrese el id");
	String nombre = JOptionPane.showInputDialog("Ingrese el nombre");
	String rutina = JOptionPane.showInputDialog("Ingrese la rutina");
        try {
            objConex.ingresarDatosBD(id, nombre, rutina);
        } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
                                
    }//GEN-LAST:event_BotonIntroducirEntrenoActionPerformed

    private void BotonCalculaRitmosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCalculaRitmosActionPerformed
        CalculaRitmos a = new CalculaRitmos();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonCalculaRitmosActionPerformed

    private void BotonVerEntrenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerEntrenosActionPerformed
        // TODO add your handling code here:
        VerEntrenos a= new VerEntrenos();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonVerEntrenosActionPerformed

    private void BotonTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTimerActionPerformed
        Temporizador a= new Temporizador();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonTimerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCalculaPorcentaje;
    private javax.swing.JButton BotonCalculaRM;
    private javax.swing.JButton BotonCalculaRitmos;
    private javax.swing.JButton BotonIntroducirEntreno;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton BotonTimer;
    private javax.swing.JButton BotonVerEntrenos;
    // End of variables declaration//GEN-END:variables

    
}

